[Distribution]
Distribution=amazonlinux
# pin release to 2023.10.20260216 since 2023.10.20260302 is installing
# kernel6.18-libbpf which is incompatible with kernel 6.12
Release=2023.10.20260216

[Build]
ToolsTreeDistribution=fedora
CacheOnly=auto
Incremental=yes

[Output]
Format=none
