ARTIFACT_BASE_URL=https://github.com/containerd/nerdctl/releases/download/v2.3.3

AARCH64_ARTIFACT=nerdctl-full-2.3.3-linux-arm64.tar.gz
AARCH64_256_DIGEST=2322f29f451189dd790b5d7c599b4600c210ff0f2c10244308a8e6a024274066

X86_64_ARTIFACT=nerdctl-full-2.3.3-linux-amd64.tar.gz
X86_64_256_DIGEST=8d39a120d8414e3aff15ac05accf51bbbad6baf54764ae709b09087e4544c1ad

# These versions were read from the nerdctl-full archive above.
# PLEASE DO NOT UPDATE THESE MANUALLY
NERDCTL_VERSION=2.3.3
CONTAINERD_VERSION=2.3.2
RUNC_VERSION=1.4.3
BUILDKIT_VERSION=0.31.0
CNI_PLUGINS_VERSION=1.9.1
