ARTIFACT_BASE_URL=https://github.com/containerd/nerdctl/releases/download/v2.3.5

AARCH64_ARTIFACT=nerdctl-full-2.3.5-linux-arm64.tar.gz
AARCH64_256_DIGEST=6e4b687f1d138e750a3c8372abc0f81d3d7490b6359c48c0562fc7dfe98859b2

X86_64_ARTIFACT=nerdctl-full-2.3.5-linux-amd64.tar.gz
X86_64_256_DIGEST=b697295c623639734aaab737523c808fd3cc8d3046039fd94fff1744e4c317aa

# These versions were read from the nerdctl-full archive above.
# PLEASE DO NOT UPDATE THESE MANUALLY
NERDCTL_VERSION=2.3.5
CONTAINERD_VERSION=2.3.3
RUNC_VERSION=1.5.1
BUILDKIT_VERSION=0.31.2
CNI_PLUGINS_VERSION=1.9.1
