ARTIFACT_BASE_URL=https://github.com/containerd/nerdctl/releases/download/v2.3.4

AARCH64_ARTIFACT=nerdctl-full-2.3.4-linux-arm64.tar.gz
AARCH64_256_DIGEST=117d65c3992e67fc4449dd501c8fba19c1d9cbf5a01fd63d68e778888f2f46e0

X86_64_ARTIFACT=nerdctl-full-2.3.4-linux-amd64.tar.gz
X86_64_256_DIGEST=40a80a6eec6fc4f225473a87946c2098821b6ec31becef0120c8a50d7b4e432c

# These versions were read from the nerdctl-full archive above.
# PLEASE DO NOT UPDATE THESE MANUALLY
NERDCTL_VERSION=2.3.4
CONTAINERD_VERSION=2.3.2
RUNC_VERSION=1.5.0
BUILDKIT_VERSION=0.31.1
CNI_PLUGINS_VERSION=1.9.1
