name: Push Container Image to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'deps/full-os.conf'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  push-container-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64, x86-64]
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          sparse-checkout: |
            bin/
            deps/full-os.conf
      - name: Extract github runID from full-os.conf
        id: vars
        run: |
          # Artifacts follow the name "finch-al2023-os-image-arm64-<run_id>.qcow2"
          run_id=$(grep 'AARCH64_ARTIFACT=' deps/full-os.conf | grep -oP '\d+(?=\.qcow2)')
          echo "run_id=${run_id}" >> $GITHUB_OUTPUT
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
        with:
          role-to-assume: ${{ secrets.ROLE }}
          aws-region: ${{ secrets.REGION }}
          role-session-name: push-container-image-session
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@d539f0932e70871a027e9d5a9d8fc38589180a64 # v2.1.6
      - name: Install skopeo
        run: |
          sudo apt-get update
          sudo apt-get install -y skopeo
      - name: Download container image tarball from S3
        run: |
          filename="finch-al2023-container-with-kernel-${{ matrix.arch }}-${{ steps.vars.outputs.run_id }}.tar"
          aws s3 cp \
            "s3://${{ secrets.DEPENDENCY_BUCKET_NAME }}/${filename}" \
            container-with-kernel-image.tar \
            --region "${{ secrets.DEPENDENCY_BUCKET_REGION }}"
      # Get the uploaded date of this os image and construct the version string.
      # This way, even if the build-os workflow and this workflow run on different days, the image in our ECR repo
      # will have the correct timestamp in its version string (the datetime when it was built).
      - name: Parse upload datetime of container image tarball from S3
        id: parse-upload-datetime
        run: |
          filename="finch-al2023-container-with-kernel-${{ matrix.arch }}-${{ steps.vars.outputs.run_id }}.tar"
          upload_datetime=$(aws s3 ls "s3://${{ secrets.DEPENDENCY_BUCKET_NAME }}/${filename}" --region "${{ secrets.DEPENDENCY_BUCKET_REGION }}" | sort | tail -n 1 | awk '{print $1, $2}')
          run_id="${{ steps.vars.outputs.run_id }}"
          version=$(date -u -d "${upload_datetime}" +'%Y.%-m.%-d')-build-${run_id}-${{ matrix.arch }}-with-kernel
          echo "version=${version}" >> $GITHUB_OUTPUT
      - name: Push container image to ECR
        run: |
          skopeo copy \
            "oci-archive:container-with-kernel-image.tar" \
            docker://"${{ secrets.ROOTFS_IMAGE_ECR_REPOSITORY_NAME }}:${{ steps.parse-upload-datetime.outputs.version }}"
      - name: Delete old ECR images
        run: |
          bash bin/clean-ecr-images.sh \
            --repo "${{ secrets.ROOTFS_IMAGE_ECR_REPOSITORY_NAME }}" \
            --arch "${{ matrix.arch }}" \
            --keep-tag "${{ steps.parse-upload-datetime.outputs.version }}"
      # Because tags are immutable in ECR, we have to delete the existing latest-{arch} tag first
      # Note that this does not actually delete the image because the image in question
      # has two tags, e.g.: x86-64-with-kernel-22922664487, latest-x86-64
      - name: Delete existing latest tag from ECR
        run: |
          REPO="${{ secrets.ROOTFS_IMAGE_ECR_REPOSITORY_NAME }}"
          aws ecr batch-delete-image \
            --repository-name "${REPO##*/}" \
            --image-ids imageTag="latest-${{ matrix.arch }}"
      - name: Tag container image as latest
        run: |
          skopeo copy \
            "oci-archive:container-with-kernel-image.tar" \
            docker://"${{ secrets.ROOTFS_IMAGE_ECR_REPOSITORY_NAME }}:latest-${{ matrix.arch }}"
