name: CI
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  testjob:
    runs-on: [self-hosted, macos, arm64, 11, release]
    steps:
    - uses: actions/checkout@v3
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      shell: zsh {0}
      
