name: test-filemonitor
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
defaults:
  run:
    shell: zsh
jobs:
  testjob:
    runs-on: [self-hosted, macos, arm64, 11, release]
    steps:
    - uses: actions/checkout@v3
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      
